query userGroupList($sortBy: SortByEnum, $page: Int, $count: Int, $_id: String!) {
	userGroupList(_id: $_id) {
		totalCount
		list {
			_id
			name
			description
			createdAt
			updatedAt
		}
		rawList
	}
}
