mutation removePermissionFromRBACRoleBatch($input: RemovePermissionFromRBACRoleBatchInput!) {
	removePermissionFromRBACRoleBatch(input: $input) {
		_id
		name
		description
		createdAt
		updatedAt
	}
}
