query rbacRoleList($sortBy: SortByEnum, $page: Int, $count: Int, $userPoolId: String!) {
	rbacRoleList(userPoolId: $userPoolId, sortBy: $sortBy, page: $page, count: $count) {
		totalCount
		list {
			_id
			name
			description
			createdAt
			updatedAt
		}
	}
}
