mutation revokeRBACRoleFromUser($sortBy: SortByEnum, $page: Int, $count: Int, $input: RevokeRBACRoleFromUserInput!){
    revokeRBACRoleFromUser(input: $input){
        _id
        userPoolId
        name
        description
        createdAt
        updatedAt
        permissions{
            totalCount
            list{
                _id
                name
                userPoolId
                createdAt
                updatedAt
                description
            }
        }
        users(sortBy: $sortBy, page: $page, count: $count){
            list{
                _id
                email
                unionid
                openid
                emailVerified
                phone
                phoneVerified
                username
                nickname
                company
                photo
                browser
                device
                password
                registerInClient
                registerMethod
                oauth
                token
                tokenExpiredAt
                loginsCount
                lastLogin
                lastIP
                signedUp
                blocked
                isDeleted
                name
                givenName
                familyName
                middleName
                profile
                preferredUsername
                website
                gender
                birthdate
                zoneinfo
                locale
                address
                formatted
                streetAddress
                locality
                region
                postalCode
                country
                updatedAt
                group{
                    _id
                    name
                    descriptions
                    client
                    permissions
                    createdAt
                }
                clientType{
                    _id
                    name
                    description
                    image
                    example
                }
                userLocation{
                    _id
                    user{
                        _id
                        username
                        email
                        unionid
                        openid
                        emailVerified
                        phone
                        phoneVerified
                        nickname
                        company
                        photo
                        browser
                        password
                        registerInClient
                        registerMethod
                        oauth
                        token
                        tokenExpiredAt
                        loginsCount
                        lastLogin
                        lastIP
                        signedUp
                        blocked
                        isDeleted
                        device
                        name
                        givenName
                        familyName
                        middleName
                        profile
                        preferredUsername
                        website
                        gender
                        birthdate
                        zoneinfo
                        locale
                        address
                        formatted
                        streetAddress
                        locality
                        region
                        postalCode
                        country
                        updatedAt
                        oldPassword
                    }
                    userPool{
                        _id
                        user{
                            _id
                            username
                            email
                            unionid
                            openid
                            emailVerified
                            phone
                            phoneVerified
                            nickname
                            company
                            photo
                            browser
                            password
                            registerInClient
                            registerMethod
                            oauth
                            token
                            tokenExpiredAt
                            loginsCount
                            lastLogin
                            lastIP
                            signedUp
                            blocked
                            isDeleted
                            device
                            name
                            givenName
                            familyName
                            middleName
                            profile
                            preferredUsername
                            website
                            gender
                            birthdate
                            zoneinfo
                            locale
                            address
                            formatted
                            streetAddress
                            locality
                            region
                            postalCode
                            country
                            updatedAt
                            oldPassword
                        }
                        clientType{
                            _id
                            name
                            description
                            image
                            example
                        }
                        userPoolTypes{
                            _id
                            name
                            description
                            image
                            example
                        }
                        usersCount
                        logo
                        emailVerifiedDefault
                        registerDisabled
                        showWXMPQRCode
                        useMiniLogin
                        useSelfWxapp
                        allowedOrigins
                        name
                        secret
                        token
                        descriptions
                        jwtExpired
                        createdAt
                        isDeleted
                        frequentRegisterCheck{
                            timeInterval
                            limit
                            enable
                        }
                        loginFailCheck{
                            timeInterval
                            limit
                            enable
                        }
                        enableEmail
                        changePhoneStrategy{
                            verifyOldPhone
                        }
                        changeEmailStrategy{
                            verifyOldEmail
                        }
                        qrcodeLoginStrategy{
                            qrcodeExpiresAfter
                            returnFullUserInfo
                            allowExchangeUserInfoFromBrowser
                            ticketExpiresAfter
                        }
                    }
                    when
                    where
                }
                userLoginHistory{
                    list{
                        _id
                        user{
                            _id
                            username
                            email
                            unionid
                            openid
                            emailVerified
                            phone
                            phoneVerified
                            nickname
                            company
                            photo
                            browser
                            password
                            registerInClient
                            registerMethod
                            oauth
                            token
                            tokenExpiredAt
                            loginsCount
                            lastLogin
                            lastIP
                            signedUp
                            blocked
                            isDeleted
                            device
                            name
                            givenName
                            familyName
                            middleName
                            profile
                            preferredUsername
                            website
                            gender
                            birthdate
                            zoneinfo
                            locale
                            address
                            formatted
                            streetAddress
                            locality
                            region
                            postalCode
                            country
                            updatedAt
                            oldPassword
                        }
                        when
                        client{
                            _id
                            user{
                                _id
                                username
                                email
                                unionid
                                openid
                                emailVerified
                                phone
                                phoneVerified
                                nickname
                                company
                                photo
                                browser
                                password
                                registerInClient
                                registerMethod
                                oauth
                                token
                                tokenExpiredAt
                                loginsCount
                                lastLogin
                                lastIP
                                signedUp
                                blocked
                                isDeleted
                                device
                                name
                                givenName
                                familyName
                                middleName
                                profile
                                preferredUsername
                                website
                                gender
                                birthdate
                                zoneinfo
                                locale
                                address
                                formatted
                                streetAddress
                                locality
                                region
                                postalCode
                                country
                                updatedAt
                                oldPassword
                            }
                            clientType{
                                _id
                                name
                                description
                                image
                                example
                            }
                            userPoolTypes{
                                _id
                                name
                                description
                                image
                                example
                            }
                            usersCount
                            logo
                            emailVerifiedDefault
                            registerDisabled
                            showWXMPQRCode
                            useMiniLogin
                            useSelfWxapp
                            allowedOrigins
                            name
                            secret
                            token
                            descriptions
                            jwtExpired
                            createdAt
                            isDeleted
                            frequentRegisterCheck{
                                timeInterval
                                limit
                                enable
                            }
                            loginFailCheck{
                                timeInterval
                                limit
                                enable
                            }
                            enableEmail
                            changePhoneStrategy{
                                verifyOldPhone
                            }
                            changeEmailStrategy{
                                verifyOldEmail
                            }
                            qrcodeLoginStrategy{
                                qrcodeExpiresAfter
                                returnFullUserInfo
                                allowExchangeUserInfoFromBrowser
                                ticketExpiresAfter
                            }
                        }
                        success
                        ip
                        result
                        device
                        browser
                    }
                    totalCount
                }
                systemApplicationType{
                    _id
                    name
                    descriptions
                    price
                }
            }
            totalCount
        }
    }
}