query users($registerInClient: String, $page: Int, $count: Int, $populate: Boolean) {
	users(registerInClient: $registerInClient, page: $page, count: $count, populate: $populate) {
		totalCount
		list {
			_id
			email
			phone
			emailVerified
			username
			nickname
			unionid
			openid
			company
			photo
			browser
			device
			registerInClient
			registerMethod
			oauth
			token
			tokenExpiredAt
			loginsCount
			lastLogin
			lastIP
			signedUp
			blocked
			isDeleted
			group {
				_id
				name
				descriptions
				createdAt
			}
			clientType {
				_id
				name
				description
				image
				example
			}
			userLocation {
				_id
				when
				where
			}
			userLoginHistory {
				totalCount
				list {
					_id
					when
					success
					ip
					result
					device
					browser
				}
			}
			systemApplicationType {
				_id
				name
				descriptions
				price
			}
		}
	}
}
